[book]
authors = ["Leon"]
language = "en"
multilingual = false
src = "src"
title = "Dora-rs文档"

[output.html]
fold.enable = true
git-repository-url = "https://github.com/drindr/dora-by-examples"
additional-css = ["assets/langtabs.css"]
additional-js = ["assets/langtabs.js"]

[preprocessor.langtabs]
command = "mdbook-langtabs"

[preprocessor.alerts]
